name: deploy-dev

on:
  workflow_dispatch:
  push:
    branches:
      - '**' # Fix wildcard to match all branches

env:
  RESOURCE_GROUP_DEV: BCSAI2024-DEVOPS-STUDENTS-B-DEV
  SUBSCRIPTION_ID_DEV: e0b9cada-61bc-4b5a-bd7a-52c606726b3b

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Validate Bicep file
      - name: Validate Bicep template
        run: az bicep build --file ./main.bicep

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Azure login
      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy the Bicep template
      - name: Deploy to Azure
        uses: azure/arm-deploy@v2
        with:
          subscriptionId: ${{ env.SUBSCRIPTION_ID_DEV }}
          resourceGroupName: ${{ env.RESOURCE_GROUP_DEV }}
          template: ./main.bicep
          parameters: ./parameters/dev.bicepparam
          deploymentName: deploy-dev-${{ github.run_id }}
          enable-detailed-trace: true # Enable detailed logs for debugging
